apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: mein-nginx       # Muss exakt zum Label im Deployment passen
  ports:
    - protocol: TCP
      port: 80            # Port im Service
      targetPort: 80      # Port im Container
  type: ClusterIP         # Nur intern erreichbar