apiVersion: v1
kind: Pod
metadata:
  name: schreib-pod
  namespace: default
spec:
  containers:
  - name: writer
    image: busybox
    # Schreibt das Datum in eine Datei und wartet dann
    command: ["/bin/sh", "-c", "echo 'Ich war hier am $(date)' >> /daten/log.txt && sleep 3600"]
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
    volumeMounts:
    - name: mein-volume
      mountPath: /daten
  volumes:
  - name: mein-volume
    persistentVolumeClaim:
      claimName: mein-speicher-antrag